# Generated by Django 2.0 on 2018-01-06 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('manuscript', 'Manuscript'), ('image', 'Image'), ('contract', 'Contract'), ('amendment', 'Contract amendment')], max_length=10)),
                ('attachment', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('publication_type', models.CharField(choices=[('collection', 'Anthology, collection, or magazine'), ('book', 'Book'), ('series', 'Series'), ('story', 'Short Story')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.Actor')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.Group')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publication.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('solicited', 'Solicited'), ('query_received', 'Query received'), ('query_approved', 'Query approved'), ('query_rejected', 'Query rejected'), ('manuscript_received', 'Manuscript recieved'), ('manuscript_approved', 'Manuscript approved'), ('manuscript_rejected', 'Manuscript rejected'), ('contracted_created', 'Contract created'), ('contract_sent', 'Contract sent'), ('contract_approved', 'Contract approved'), ('contract_rejected', 'Contract rejected'), ('contract_changes_requested', 'Contract changes requested'), ('contract_signed', 'Contract signed'), ('content_edits_pass', 'Content edits pass'), ('content_edits_approved', 'Content edits approved'), ('content_edits_changes_requested', 'Content edits changes requested'), ('copy_edits_pass', 'Copy edits pass'), ('copy_edits_approved', 'Copy edits approved'), ('copy_edits_changes_requested', 'Copy edits changes requested'), ('layout_pass', 'Layout pass'), ('layout_test_pass', 'Layout test sent'), ('layout_test_approved', 'Layout test approved'), ('layout_test_changes_requested', 'Layout test changes requested'), ('ebook_pass', 'Ebook pass'), ('ebook_test_pass', 'Ebook test sent'), ('ebook_test_approved', 'Ebook test approved'), ('ebook_test_changes_requested', 'Ebook test changes requested'), ('cover_art_solicted', 'Cover art solicited'), ('cover_art_received', 'Cover art received'), ('cover_art_approved', 'Cover art approved'), ('cover_art_changes_requested', 'Cover art changes requested'), ('blurb_created', 'Blurb created'), ('blurb_approved', 'Blurb approved'), ('blurb_changes_requested', 'Blurb changes requested'), ('arc_sent', 'ARC sent'), ('arc_quote_received', 'ARC quote received'), ('ISBN_print', 'ISBN created for print'), ('ISBN_ebook', 'ISBN created for ebook'), ('listed_amazon', 'Listed on Amazon'), ('listed_bn', 'Listed on B&N'), ('listed_goodreads', 'Listed on Good Reads')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.Publication')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.Publication'),
        ),
    ]
