# Generated by Django 2.0 on 2018-02-04 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('manuscript', 'Manuscript'), ('image', 'Image'), ('contract', 'Contract'), ('amendment', 'Contract amendment')], max_length=10)),
                ('attachment', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=1000)),
                ('publication_type', models.CharField(choices=[('collection', 'Anthology, collection, or magazine'), ('book', 'Book'), ('series', 'Series'), ('story', 'Short Story')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.Actor')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.Group')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publication.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('created', 'Publication created'), ('query_received', 'Query received'), ('query_approved', 'Query approved'), ('query_rejected', 'Query rejected'), ('solicited', 'Solicited'), ('manuscript_received', 'Manuscript recieved'), ('manuscript_approved', 'Manuscript approved'), ('manuscript_rejected', 'Manuscript rejected'), ('contract_pass', 'Contract pass'), ('contract_sent', 'Contract sent'), ('contract_changes_requested', 'Contract changes requested'), ('contract_approved', 'Contract approved'), ('contract_rejected', 'Contract rejected'), ('contract_signed', 'Contract signed'), ('content_edits_pass', 'Content edits pass'), ('content_edits_sent', 'Content edits sent'), ('content_edits_changes_requested', 'Content edits changes requested'), ('content_edits_approved', 'Content edits approved'), ('copy_edits_pass', 'Copy edits pass'), ('copy_edits_sent', 'Copy edits sent'), ('copy_edits_changes_requested', 'Copy edits changes requested'), ('copy_edits_approved', 'Copy edits approved'), ('layout_pass', 'Layout pass'), ('layout_sent', 'Layout sent'), ('layout_changes_requested', 'Layout changes requested'), ('layout_approved', 'Layout approved'), ('layout_skipped', 'Layout skipped'), ('ebook_pass', 'Ebook pass'), ('ebook_sent', 'Ebook sent'), ('ebook_changes_requested', 'Ebook changes requested'), ('ebook_approved', 'Ebook approved'), ('ebook_skipped', 'Ebook skipped'), ('cover_art_provided', 'Cover art provided'), ('cover_art_solicted', 'Cover art solicited'), ('cover_art_received', 'Cover art received'), ('cover_art_pass', 'Cover art pass'), ('cover_art_sent', 'Cover art sent'), ('cover_art_changes_requested', 'Cover art changes requested'), ('cover_art_approved', 'Cover art approved'), ('cover_art_skipped', 'Cover art skipped'), ('interior_art_provided', 'Interior art provided'), ('interior_art_solicted', 'Interior art solicited'), ('interior_art_received', 'Interior art received'), ('interior_art_pass', 'Interior art pass'), ('interior_art_sent', 'Interior art sent'), ('interior_art_changes_requested', 'Interior art changes requested'), ('interior_art_approved', 'Interior art approved'), ('blurb_pass', 'Blurb pass'), ('blurb_sent', 'Blurb sent'), ('blurb_changes_requested', 'Blurb changes requested'), ('blurb_approved', 'Blurb approved'), ('arc_sent', 'ARC sent'), ('arc_quote_received', 'ARC quote received'), ('ISBN_print', 'ISBN created for print'), ('ISBN_ebook', 'ISBN created for ebook'), ('print_service_pass', 'Print service file pass'), ('print_service_sent', 'Print service file sent'), ('print_service_changes_requested', 'Print service changes requested'), ('print_service_approved', 'Print service file approved'), ('listed_channel', 'Listed on sales channel'), ('listed_goodreads', 'Listed on Good Reads'), ('review_solicted', 'Review solicited'), ('review_received', 'Review received'), ('review_posted', 'Review posted'), ('sale_discount_created', 'Sale or discount created'), ('sale_discount_ended', 'Sale or discount ended')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.Publication')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.Step'),
        ),
    ]
